test run

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -51,38 +51,40 @@ jobs:
         echo "Checking installation directory..."
         ls -l $HOME/.config/games-tui
         ls -l $HOME/.local/share/games-tui
-
-        games-tui
       shell: bash
 
-
-    - name: Test Makefile on macOS
-      if: matrix.os == 'macos-latest'
+    - name: Run application (Ubuntu)
       run: |
-        set -x
-        make install
-        make build
-        make install_binary
-        echo "Checking installed binary..."
-        ls -l /usr/local/bin/games-tui || echo "Binary not found!"
-        
-        echo "Checking installation directory..."
-        ls -l "/Users/$(whoami)/Library/Application Support/games-tui/config" || echo "Config data not found!"
-        ls -l "/Users/$(whoami)/Library/Application Support/games-tui/data" || echo "App data not found!"
-      shell: bash
+        TERM=xterm ./dist/games-tui
 
 
-    - name: Test Makefile on Windows
-      if: matrix.os == 'windows-latest'
-      run: |
-        set -x
-        make install
-        make build
-        make install_binary
-        echo "Checking installed binary..."
-        dir "C:\Program Files\games-tui\games-tui.exe" || echo "Binary not found!"
-
-        echo "Checking installation directory..."
-        dir "C:\Program Files\games-tui\config" || echo "Config data not found!"
-        dir "C:\Program Files\games-tui\data" || echo "App data not found!"
-      shell: bash
+    # - name: Test Makefile on macOS
+    #   if: matrix.os == 'macos-latest'
+    #   run: |
+    #     set -x
+    #     make install
+    #     make build
+    #     make install_binary
+    #     echo "Checking installed binary..."
+    #     ls -l /usr/local/bin/games-tui || echo "Binary not found!"
+    #     
+    #     echo "Checking installation directory..."
+    #     ls -l "/Users/$(whoami)/Library/Application Support/games-tui/config" || echo "Config data not found!"
+    #     ls -l "/Users/$(whoami)/Library/Application Support/games-tui/data" || echo "App data not found!"
+    #   shell: bash
+    #
+    #
+    # - name: Test Makefile on Windows
+    #   if: matrix.os == 'windows-latest'
+    #   run: |
+    #     set -x
+    #     make install
+    #     make build
+    #     make install_binary
+    #     echo "Checking installed binary..."
+    #     dir "C:\Program Files\games-tui\games-tui.exe" || echo "Binary not found!"
+    #
+    #     echo "Checking installation directory..."
+    #     dir "C:\Program Files\games-tui\config" || echo "Config data not found!"
+    #     dir "C:\Program Files\games-tui\data" || echo "App data not found!"
+    #   shell: bash
