make

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -68,17 +68,17 @@ jobs:
         ls -l "/Users/$(whoami)/Library/Application Support/games-tui/data" || echo "App data not found!"
       shell: bash
 
-    # - name: Test Makefile on Windows
-    #   if: matrix.os == 'windows-latest'
-    #   run: |
-    #     set -x
-    #     make install
-    #     make build
-    #     make install_binary
-    #     echo "Checking installed binary..."
-    #     dir "C:\Program Files\games-tui\games-tui.exe" || echo "Binary not found!"
-    #
-    #     echo "Checking installation directory..."
-    #     dir "C:\Program Files\games-tui\config" || echo "Config data not found!"
-    #     dir "C:\Program Files\games-tui\data" || echo "App data not found!"
-    #   shell: bash
+    - name: Test Makefile on Windows
+      if: matrix.os == 'windows-latest'
+      run: |
+        set -x
+        make install
+        make build
+        make install_binary
+        echo "Checking installed binary..."
+        dir "C:\Program Files\games-tui\games-tui.exe" || echo "Binary not found!"
+
+        echo "Checking installation directory..."
+        dir "C:\Users\$(whoami)\AppData\Roaming\games-tui\config" || echo "Config data not found!"
+        dir "C:\Users\$(whoami)\AppData\Roaming\games-tui\data" || echo "App data not found!"
+      shell: bash
